services:
     frontend:
          build: ./client
          image: mern-frontend # Name of the image
          container_name: frontend
          restart: always
          depends_on:
               - backend
          networks:
               - app-network

     backend:
          build: ./server
          container_name: backend
          restart: always
          ports:
               - "9000:9000"
          env_file:
               - ./server/.env
          environment:
               NODE_ENV: production
          depends_on:
               - mongo
          networks:
               - app-network

     mongo:
          image: mongo:8.0.6
          container_name: mongo
          restart: always
          volumes:
               - ./data:/data/db
          ports:
               - "27017:27017"
          networks:
               - app-network

     nginx:
          image: nginx:latest
          container_name: nginx
          restart: always
          ports:
               - "80:80"
          volumes:
               - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Link Nginx config
               - ./client/dist:/usr/share/nginx/html # Static files for frontend
          depends_on:
               - frontend
               - backend
          networks:
               - app-network

networks:
     app-network:
          driver: bridge
